name 'powerline-chef-apiserver'
maintainer 'powerline'
maintainer_email 'austin at powerli dot ne'
license 'all_rights'
version '0.1.0'

depends 'powerline-chef-baseline'
depends 'application'
depends 'poise-python'
depends 'supervisor'
depends 'nginx'
depends 'rabbitmq'
depends 'aws-sdk'
depends 'aws'
depends 'composer'

depends 'pl-nginx'
depends 'pl-php5'
depends 'pl-rabbitmq'
depends 'pl-server'
depends 'pl-supervisor'
depends 'pl-symfony'
