---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[pl-php5::setup]
      - recipe[pl-php5::configure-fpm]
    attributes:
      env: test
