---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
suites:
  - name: default
    run_list:
      - recipe[pl-server::default]
      - recipe[pl-server::setup-dirs]
      - recipe[pl-server::setup-packages]
    attributes:
      env: 'test'
