---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

<% creds = YAML.load_file('.credentials.yml') %>

suites:
  - name: default
    run_list:
      - recipe[pl-symfony::setup]
    attributes:
      env: test
      aws_access_key: <%= creds['aws']['access_key'] %>
      aws_secret_key: <%= creds['aws']['secret_key'] %>
